# Force C++23 modules support before project() is invoked
set(CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API TRUE CACHE INTERNAL "")
set(CMAKE_CXX_STANDARD 23 CACHE INTERNAL "")
set(CMAKE_CXX_STANDARD_REQUIRED TRUE CACHE INTERNAL "")